DG: false
FSGD: false
PCB: false
adv: 0.0
aiter: 10
arcface: false
batchsize: 16
circle: true
color_jitter: false
contrast: false
cosface: false
cosine: false
data_dir: /content/VRIC_rename/rename
droprate: 0.5
erasing_p: 0.5
fp16: false
gpu_ids: '0'
ibn: false
ins_gamma: 32
instance: false
lifted: false
linear_num: 512
lr: 0.01
name: SWINV1_CP_2
nclasses: 2811
sphere: false
stride: 2
total_epoch: 60
train_all: false
triplet: false
use_NAS: false
use_convnext: false
use_dense: false
use_efficient: false
use_hr: false
use_swin: true
use_swinv2: false
warm_epoch: 5
weight_decay: 0.0005
